# WandB hyperparameter sweep configuration file

program: src/ml_ops_project/train.py
method: bayes
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
name: mlops_sweep
project: MLOps-Project
entity: MLOpsss
metric:
    goal: minimize
    name: val_loss
parameters:
    optimizer.lr:
        min: 1e-5
        max: 5e-4
        distribution: log_uniform_values
    training.batch_size:
        values: [16, 64, 128]
run_cap: 10
