batch_size: 64
max_epochs: 5
seed: 23
checkpoint_dir: "checkpoints/"
num_workers: 4
persistent_workers: true
pin_memory: true # Set to true if using GPU for faster data transfer
# learning rate etc. managed in optimizer/
