workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-8
        acceleratorType: NVIDIA_TESLA_T4
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/dtumlops-484016/ml-ops-project-artifact-reg/ml-ops-proj-instance:latest
        env:
          - name: WANDB_API_KEY
            value: $WANDB_API_KEY_PROJ
          - name: WANDB_PROJECT
            value: $WANDB_PROJECT_PROJ
          - name: WANDB_ENTITY
            value: $WANDB_ENTITY_PROJ
        # This image was automatically built and pushed to Artifact Registry
        # using the cloudbuild.yaml file in the GCP/ folder.
