defaults:
  - model: distilbert
  - optimizer: adam
  - training: default
  - wandb: default
  - _self_  # essentially allows the main config to override defaults

experiment_name: "baseline_distilbert"
data_dir: "data/"  # or "gcs/ml_ops_project_g7/data" for Vertex AI

hydra:
  job:
    chdir: False

inference:
  enabled: False
  registry: "wandb-registry-model_registry"
  collection: "sentiment_classifier_models"
  alias: "inference"

cloud:
  BUCKET_NAME: "ml_ops_project_g7"